apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner

    template:
      engineVersion: v2
      data:
        POSTGRES_USER: '{{ `{{ .username }}` }}'
        POSTGRES_PASSWORD: '{{ `{{ .password }}` }}'
        POSTGRES_DB: '{{ `{{ .database }}` }}'
        DATABASE_URL: '{{ `{{ .url }}` }}'

  dataFrom:
    - extract:
        key: notes/postgres