apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "notes-be.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: notes
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
