apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace.app }}
spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: notes
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: notes
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend

    spec:
      nodeSelector:
        workload: backend

      tolerations:
        - key: {{ .Values.backend.toleration.key | quote }}
          operator: Equal
          value: {{ .Values.backend.toleration.value | quote }}
          effect: {{ .Values.backend.toleration.effect }}

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: 3000
            
          resources:
            requests:
              cpu: "250m"      # Minimal CPU required (0.25 core)
              memory: "64Mi"   # Minimal memory required (64 Megabytes)
            limits:
              cpu: "500m"      # Maximum CPU allowed (0.5 core)
              memory: "128Mi"  # Maximum memory allowed (128 Megabytes)

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/readyz
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL