{{ with .Values.postgres.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ $.Values.namespace.app }}

type: Opaque
stringData:
  POSTGRES_USER: {{ .username | quote }}
  POSTGRES_PASSWORD:  {{ .password | quote }}
  POSTGRES_DB: {{ .database | quote }}

  DATABASE_URL: {{ .url | quote}}

{{ end }}