prometheusRelease: monitoring

backend:
  enabled: true

  namespace: app

  selector:
    appName: notes
    component: backend

  metrics:
    port: http
    path: /metrics
    interval: 15s

alerts:
  enabled: true

  backendHighErrorRate:
    enabled: true
    threshold: 0.05
    duration: 5m
    severity: warning

  backendCPUAboveHPA:
    enabled: true
    cpuThreshold: 30
    duration: 5m
    severity: warning