apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: notes
  namespace: gitops

spec:
  generators:
    - list:
        elements:
          - name: notes-infrastructure
            chartPath: helm/infrastructure
            releaseName: notes-infra
            namespace: edge
            syncWave: "0"

          - name: notes-database
            chartPath: helm/database
            releaseName: notes-db
            namespace: app
            syncWave: "1"

          - name: notes-backend
            chartPath: helm/backend
            releaseName: notes-be
            namespace: app
            syncWave: "2"

          - name: notes-frontend
            chartPath: helm/frontend
            releaseName: notes-fe
            namespace: app
            syncWave: "3"
          
          - name: notes-monitoring
            chartPath: helm/monitoring
            releaseName: notes-monitor
            namespace: monitoring
            syncWave: "4"

  template:
    metadata:
      name: "{{ name }}"
      namespace: gitops
      annotations:
        argocd.argoproj.io/sync-wave: "{{ syncWave }}"

    spec:
      project: default

      source:
        repoURL: https://github.com/tunang/fsoft-docker-k8s-lab.git

        targetRevision: main

        path: "{{ chartPath }}"

        helm:
          releaseName: "{{ releaseName }}"

          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc

        namespace: "{{ namespace }}"

      syncPolicy:

        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
