apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: notes
  namespace: gitops

spec:
  project: default

  # ==========================================================
  # SOURCE
  # Where Argo CD gets the desired state
  # ==========================================================

  source:
    repoURL: https://github.com/tunang/fsoft-docker-k8s-lab.git
    

    # Git branch
    targetRevision: main

    # Location of the Helm chart inside the repository
    path: helm

    helm:
      # Same Helm release name you were already using
      releaseName: notes

      valueFiles:
        - values.yaml

  # ==========================================================
  # DESTINATION
  # Where Argo CD deploys the application
  # ==========================================================

  destination:

    # Kubernetes cluster where Argo CD itself is running
    server: https://kubernetes.default.svc

    # Notes application namespace
    namespace: app

  # ==========================================================
  # SYNC POLICY
  # ==========================================================

  syncPolicy:

    automated:

      # Git changed -> automatically update Kubernetes
      prune: true

      # Kubernetes manually changed -> restore Git state
      selfHeal: true

    syncOptions:

      # Create namespace "app" if it doesn't exist
      - CreateNamespace=true