apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "notes-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: database

spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: notes
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database

  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
