apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: {{ .Values.namespace }}

  labels:
    {{- include "notes-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: database

spec:
  serviceName: postgres

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: notes
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database

  template:
    metadata:
      labels:
        app.kubernetes.io/name: notes
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database

    spec:
      nodeSelector:
        workload: {{ .Values.nodeSelector.workload }}

      tolerations:
        - key: {{ .Values.toleration.key | quote }}
          operator: Equal
          value: {{ .Values.toleration.value | quote }}
          effect: {{ .Values.toleration.effect }}

      containers:
        - name: postgres

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.service.port }}

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce
        
        storageClassName: standard

        resources:
          requests:
            storage: {{ .Values.persistence.size }}
