apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.app }}

  labels:
    {{- include "notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app.kubernetes.io/name: notes
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend

  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}