apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.app }}

  labels:
    {{- include "notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: notes
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: notes
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend

    spec:
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      tolerations:
        - key: {{ .Values.frontend.toleration.key }}
          operator: {{ .Values.frontend.toleration.operator }}
          value: {{ .Values.frontend.toleration.value }}
          effect: {{ .Values.frontend.toleration.effect }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}

          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.path }}
              port: {{ .Values.frontend.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
