apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.edge }}

  labels:
    {{- include "notes-fe.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-edge

spec:
  type: {{ .Values.edgeService.type }}
  externalName: {{ .Values.edgeService.externalName }}
