apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-netpol
  namespace: {{ .Values.namespace.app }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: frontend

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Cho phép traffic từ Ingress Controller (namespace ingress-nginx)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80

  egress:
    # Cho phép frontend gọi backend (port 3000)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 3000

    # Cho phép DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
