{{- if .Values.backend.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: notes-backend
  namespace: {{ .Release.Namespace }}

  labels:
    release: {{ .Values.prometheusRelease }}

spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.backend.namespace }}

  selector:
    matchLabels:
      app.kubernetes.io/name: notes-backend
      app.kubernetes.io/component: backend

  endpoints:
    - port: {{ .Values.backend.metrics.port }}
      path: {{ .Values.backend.metrics.path }}
      interval: {{ .Values.backend.metrics.interval }}

{{- end }}